In [3]:
# Data Ecoding >> converting categorical columns into numeric
# Nominal/PHE
# label and ordinal encoding
# Target guide oedinal encoding

In [4]:
# Nominal/OHE >> Binary vector for each of the categoricals
# Example single, marred, separated
# Single [1, 0, 0]
# married: [4, 1, 0]
# Seprated: [0, 0, 1]

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({"status": ["single", "married", "separeted", "single", "married"]})

In [7]:
df

status
0     single
1    married
2  separeted
3     single
4    married

In [8]:
encoder = OneHotEncoder()

In [9]:
encoder

OneHotEncoder()

In [10]:
encoded = encoder.fit_transform(df[["status"]]).toarray()

In [11]:
encoded 

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [12]:
encoder.get_feature_names_out()

array(['status_married', 'status_separeted', 'status_single'],
      dtype=object)

In [13]:
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [14]:
encoder_df

status_married  status_separeted  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             1.0               0.0            0.0

In [15]:
encoder.transform([["single"]]).toarray()

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [16]:
# pd.get_dum()

In [17]:
pd.concat([df, encoder_df], axis = 1)

status  status_married  status_separeted  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separeted             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0

In [18]:
sns.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [19]:
#label encodeing >> assing unique label to the categories
# using map or using library
df

status
0     single
1    married
2  separeted
3     single
4    married

In [20]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [21]:
label_encoder.fit_transform(df[['status']])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [22]:
label_encoder.transform(["separated"])

ValueError: y contains previously unseen labels: 'separated'

In [ ]:
# ordinal encoding
# High School : 34
# graiate: 2
# pass greduate: 3
# phd: 4


In [ ]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({"qualification": ["HS", "CR", "PG", "PHD", "BCA"]})

In [ ]:
df

In [ ]:
encoder = OrdinalEncoder(categories=[["HS", "CR", "PG", "PHD", "BCA"]])

In [ ]:
encoder.fit_transform(df[["qualification"]])

In [ ]:
# New Data 
encoder.transform([["PG"]])

In [ ]:
# Target guide ordinal encoding
# relationship target variable 
# A lot of unique categiries
# replace the category with mean and median of respective group.


In [24]:
import pandas as pd

df = pd.DataFrame({
    'time': ["lunch", "breakfast", "dinner", "lunch", "breakfast", "lunch", "dinner", "lunch", "dinner"],
    'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]
})

In [25]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5      lunch         190
6     dinner         160
7      lunch         180
8     dinner         189

In [31]:
mean_price = df.groupby('time')['total_bill'].mean()

In [33]:
df["timne_encoder"] = df['time'].map(mean_price)

In [34]:
df

time  total_bill  timne_encoder
0      lunch         120     153.750000
1  breakfast         130     140.000000
2     dinner          90     146.333333
3      lunch         125     153.750000
4  breakfast         150     140.000000
5      lunch         190     153.750000
6     dinner         160     146.333333
7      lunch         180     153.750000
8     dinner         189     146.333333

In [35]:
sns.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]